# Generated by Django 4.1.3 on 2022-11-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="company",
        ),
    ]
