# Generated by Django 4.1.3 on 2022-11-02 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("projects", "0002_remove_project_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="companies.company",
            ),
        ),
    ]
