# Generated by Django 4.1.3 on 2022-11-01 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_remove_task_notes_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="task",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="tasks.task",
            ),
        ),
    ]
