# Generated by Django 4.1.3 on 2022-11-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="employee",
        ),
        migrations.AddField(
            model_name="company",
            name="is_employee",
            field=models.BooleanField(default=False),
        ),
    ]
