# Generated by Django 4.1.3 on 2022-11-03 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="companies.company",
            ),
        ),
    ]
