# Generated by Django 4.1.3 on 2022-11-02 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "companies",
            "0003_alter_company_options_remove_company_is_employee_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="user",
            new_name="name",
        ),
    ]
