# Generated by Django 4.1.3 on 2022-11-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_alter_employee_company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="name",
            new_name="owner",
        ),
    ]
